apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-config
data:
  40-swagger-ui.sh: |
    #! /bin/sh
    set -e
  swagger-initializer.js: |
    window.onload = function() {      
          window.ui = SwaggerUIBundle({
            urls: [
              {
              name:"petstore",
              url:"https://petstore.swagger.io/v2/swagger.json"
              }
            ],
            "dom_id": "#swagger-ui",
            deepLinking: true,
            presets: [
              SwaggerUIBundle.presets.apis,
              SwaggerUIStandalonePreset
            ],
            plugins: [
              SwaggerUIBundle.plugins.DownloadUrl
            ],
            layout: "StandaloneLayout",
            queryConfigEnabled: false,
          })
    };
